name: tikkit
description: A Reddit client for the TikTok generation
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  json_annotation: ^4.4.0
  video_player: ^2.4.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.6

flutter:
  uses-material-design: true
